export const projects = [
  {
    id: 0,
    title: 'HuskyTrack: Campus Life Tracker',
    description:
      'A full-stack web application built to help Northeastern University students discover, manage, and engage with campus events. The platform supports Students, Organizers, and Admins, enabling a complete event lifecycle from creation and publishing to registration, waitlisting, and completion.',
    tags: ['React', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'JWT', 'AWS S3', 'Docker', 'GitHub Actions'],
    year: '2025',
    role: 'Full Stack Developer',
    highlights: [
      'Built with React + TypeScript, Node.js (Express), and MongoDB',
      'Implemented advanced event search and filtering, role-based access control, and JWT authentication',
      'Integrated debounced search, URL query synchronization, and efficient frontend state management',
      'Designed a scalable backend using a layered architecture (controllers, services, repositories)',
      'Added secure image uploads with AWS S3 and automated event status updates',
      'Applied real-world engineering practices: API documentation, testing (Jest, Supertest), and CI/CD with GitHub Actions, deployed via Docker on AWS EC2',
    ],
    liveUrl: '#',
    sourceUrl: 'https://github.com/CSYE7230-group4/huskytrack',
  },
  {
    id: 1,
    title: 'DeliverEase: UI/UX Application',
    description:
      'A mobile food-ordering app concept designed using Figma and Moqups, focused on delivering a seamless and intuitive experience similar to Uber Eats and DoorDash. The project covers end-to-end user journeys, from onboarding and restaurant discovery to checkout and real-time order tracking.',
    tags: ['Figma', 'Moqups', 'UI/UX', 'Prototyping'],
    year: '2025',
    role: 'Product / UI-UX Designer',
    highlights: [
      'Designed complete user flows: onboarding, browsing, ordering, and order tracking',
      'Created high-fidelity wireframes and interactive prototypes',
      'Emphasized usability, accessibility, visual hierarchy, and design consistency',
      'Focused on user-centered design to improve clarity, efficiency, and overall experience',
    ],
    liveUrl: '#',
    sourceUrl: 'https://github.com/anishneu/Deliverease-Figma-UI-Redesign',
  },
  {
    id: 2,
    title: 'MedShop: Online Medical Store Platform',
    description:
      'A full-stack web application built to manage medical inventory, customer orders, and stock requests for an online pharmacy platform. The system focuses on reliability, scalability, and efficient backend architecture.',
    tags: ['Java', 'Spring MVC', 'Hibernate', 'JSP', 'MySQL', 'HikariCP', 'Tomcat'],
    year: '2024',
    role: 'Backend / Full Stack Developer',
    highlights: [
      'Developed using Spring MVC with Hibernate for secure session handling and database transactions',
      'Optimized database performance and connection pooling using HikariCP',
      'Implemented JSP-based views for server-side rendering',
      'Deployed on Apache Tomcat 9 using NetBeans for a stable and maintainable application',
    ],
    liveUrl: '#',
    sourceUrl: 'https://github.com/anishneu/Medshop-Online-Medical-Store',
  },
  {
    id: 3,
    title: 'Recipe Hub',
    description:
      'A full-stack web application designed to streamline recipe discovery, creation, and management through a role-based platform supporting Admins, Chefs, and General Users.',
    tags: ['React', 'Material UI', 'Bootstrap', 'Node.js', 'Express', 'MongoDB', 'REST API'],
    year: '2024',
    role: 'Full Stack Developer',
    highlights: [
      'Built with React.js, Material UI, and Bootstrap for a responsive and accessible frontend',
      'Developed scalable RESTful APIs using Node.js and Express.js, with MongoDB for flexible data storage',
      'Implemented role-based access control and tailored user experiences per role',
      'Integrated real-time food news updates to enhance user engagement',
      'Added seasonal UI elements (autumn, winter, monsoon themes) for an immersive, dynamic experience',
    ],
    liveUrl: '#',
    sourceUrl: 'https://github.com/anishneu/RecipeHub',
  },
  {
    id: 4,
    title: 'Face Detection and Gender Identification using Convolutional Neural Network',
    description:
      'A computer vision project focused on accurately predicting gender from human face images using deep learning techniques.',
    tags: ['Python', 'CNN', 'OpenCV', 'TensorFlow', 'Machine Learning'],
    year: '2022',
    role: 'ML / Software Developer',
    highlights: [
      'Trained a Convolutional Neural Network (CNN) on facial image datasets for gender classification',
      'Applied image pre-processing and noise reduction for improved accuracy',
      'Implemented Haar-Cascade face detection to localize facial regions',
      'Optimized model performance by combining convolution and max-pooling layers',
      'Used a fully connected layer for final gender prediction and result visualization',
    ],
    liveUrl: '#',
    sourceUrl: 'https://github.com/anishneu/Face-Detection-and-Gender-Recognition',
  },
  {
    id: 5,
    title: 'CovidCare: Healthcare Service System',
    description:
      'A web-based hospital management platform designed to simplify access to patient records, doctor information, appointments, and diagnostic reports.',
    tags: ['Django', 'Python', 'MySQL', 'PhpMyAdmin', 'HTML', 'CSS'],
    year: '2020',
    role: 'Full Stack Developer',
    highlights: [
      'Developed a user-friendly hospital website with patient and doctor dashboards',
      'Implemented appointment booking with real-time updates',
      'Enabled downloadable diagnostic reports for improved accessibility',
      'Built a scalable database using MySQL and phpMyAdmin to enhance performance and data management',
      'Focused on usability, efficiency, and reliable system functionality',
    ],
    liveUrl: '#',
    sourceUrl: 'https://github.com/anishneu/Covidcare-Healthcare-Service-System',
  },
];
